### PR TITLE
Downgrade h5py in requirements.txt and fix module error in annotate.py

### LINKED ISSUE #24: Fix error. Solution in comments- AttributeError: 'str' object has no attribute 'decode'
AttributeError: 'str' object has no attribute 'decode'
Fix:
Downgrade h5py.

pip install 'h5py==2.10.0' --force-reinstall
Reference:
https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

Stack Trace:
python3 annotate.py annotateCustom --image_directory=/host/Notes/SalmonModel --label=Salmon --weights=/host/mask_rcnn_coco_tf22_01082021/mask_rcnn_mmodel_0030.h5 --displayMaskedImages=True

Loading weights... /host/mask_rcnn_coco_tf22_01082021/mask_rcnn_mmodel_0030.h5
Traceback (most recent call last):
File "annotate.py", line 218, in
model.load_weights(weights_path, by_name=True)
File "/Auto-Annotate/mrcnn/model.py", line 2130, in load_weights
saving.load_weights_from_hdf5_group_by_name(f, layers)
File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 3114, in load_weights_from_hdf5_group_by_name
original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

### PR DESCRIPTION
**Pull request by huyszn**
Fixes #24. Also added an import statement to `annotate.py` to fix a `no module named 'utils'` error when I was trying to run `annotate.py`.

### CODE REVIEW

**Comment by mdhmz1** [comment]
Did you run the code both ways-> Coco and custom?

**Comment by huyszn** [comment]
I ran the code using annotateCoco and annotateCustom modes both with the COCO dataset and the COCO weights and I didn't get an error while running both of them

**Comment by mdhmz1** [comment]
Thanks.

**Review by mdhmz1 — COMMENTED** [review]
LGTM

**Pull request merged**
